apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-service
spec:
  selector:
    matchLabels:
      app: schedule-service
  template:
    metadata:
      labels:
        app: schedule-service
    spec:
      containers:
      - name: schedule-service
        image: msa-schedule-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: msa-config
---
apiVersion: v1
kind: Service
metadata:
  name: schedule-service
spec:
  selector:
    app: schedule-service
  ports:
    - port: 8000
      targetPort: 8000
